export const GET_MAILS = "GET_MAILS";
export const SET_MAILS_LOADING = "SET_LOADING";
export const SET_MAILS_SUCCESS = "SET_MAILS_SUCCESS";
export const SET_MAILS_FAIL = "SET_MAILS_FAIL";
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const GET_FILTERED_DATA = "GET_FILTERED_DATA";
export const SET_FILTERED_DATA = "SET_FILTERED_DATA";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
